const entities = {
  desertos: {
    table: "desertos",
    primaryKey: ["id"],
    columns: [
      "id",
      "num_requerimento",
      "status",
      "num_processo",
      "nome",
      "cpf_cnpj",
      "diretoria",
      "ugrhi",
      "municipio",
      "tipo_requerimento",
      "data_inicio_boletim",
      "fiscal",
      "num_oficio",
      "auto_inspecao",
      "enquadramento",
      "data_conclusao",
      "data_envio",
      "numero_ar",
      "data_entrega",
      "situacao_entrega",
      "data_manifest",
      "requerimento",
      "num_req_novo",
      "acao_final",
      "boletim",
      "created",
      "updated",
      "deleted_at",
    ],
    requiredOnCreate: ["id"],
    updatableColumns: [
      "num_requerimento",
      "status",
      "num_processo",
      "nome",
      "cpf_cnpj",
      "diretoria",
      "ugrhi",
      "municipio",
      "tipo_requerimento",
      "data_inicio_boletim",
      "fiscal",
      "num_oficio",
      "auto_inspecao",
      "enquadramento",
      "data_conclusao",
      "data_envio",
      "numero_ar",
      "data_entrega",
      "situacao_entrega",
      "data_manifest",
      "requerimento",
      "num_req_novo",
      "acao_final",
      "boletim",
      "deleted_at",
    ],
  },
  fiscalizacoes: {
    table: "fiscalizacoes",
    primaryKey: ["id"],
    columns: [
      "id",
      "nome",
      "status",
      "municipio",
      "cpf_cnpj",
      "diretoria",
      "ugrhi",
      "fiscal",
      "data_fiscalizacao",
      "coordenadas",
      "usos",
      "autos_fisc",
      "autos_soe",
      "processo_sei",
      "auto_inspecao",
      "auto_infracao",
      "enquadramento",
      "prazo_dias",
      "data_envio",
      "numero_ar",
      "data_entrega",
      "situacao_entrega",
      "data_manifest",
      "requerimento",
      "num_requerimento",
      "vai_multar",
      "boletim",
      "fotos",
      "created",
      "updated",
      "deleted_at",
    ],
    requiredOnCreate: ["id"],
    updatableColumns: [
      "nome",
      "status",
      "municipio",
      "cpf_cnpj",
      "diretoria",
      "ugrhi",
      "fiscal",
      "data_fiscalizacao",
      "coordenadas",
      "usos",
      "autos_fisc",
      "autos_soe",
      "processo_sei",
      "auto_inspecao",
      "auto_infracao",
      "enquadramento",
      "prazo_dias",
      "data_envio",
      "numero_ar",
      "data_entrega",
      "situacao_entrega",
      "data_manifest",
      "requerimento",
      "num_requerimento",
      "vai_multar",
      "boletim",
      "fotos",
      "deleted_at",
    ],
  },
  indeferimentos: {
    table: "indeferimentos",
    primaryKey: ["id"],
    columns: [
      "id",
      "num_requerimento",
      "status",
      "portaria",
      "data_publicacao",
      "diretoria",
      "motivo",
      "num_processo",
      "nome",
      "municipio",
      "tipo_requerimento",
      "notificar",
      "data_prazo",
      "novo_requerimento",
      "data_inicio_boletim",
      "fiscal",
      "num_oficio",
      "auto_inspecao",
      "auto_infracao",
      "enquadramento",
      "data_envio",
      "numero_ar",
      "data_entrega",
      "situacao_entrega",
      "requerimento",
      "num_req_novo",
      "acao_final",
      "boletim",
      "created",
      "updated",
      "deleted_at",
    ],
    requiredOnCreate: ["id"],
    updatableColumns: [
      "num_requerimento",
      "status",
      "portaria",
      "data_publicacao",
      "diretoria",
      "motivo",
      "num_processo",
      "nome",
      "municipio",
      "tipo_requerimento",
      "notificar",
      "data_prazo",
      "novo_requerimento",
      "data_inicio_boletim",
      "fiscal",
      "num_oficio",
      "auto_inspecao",
      "auto_infracao",
      "enquadramento",
      "data_envio",
      "numero_ar",
      "data_entrega",
      "situacao_entrega",
      "requerimento",
      "num_req_novo",
      "acao_final",
      "boletim",
      "created",
      "updated",
      "deleted_at",
    ],
  },
  rate_limits: {
    table: "rate_limits",
    primaryKey: ["scope", "ip_hash"],
    columns: ["scope", "ip_hash", "count", "reset_at", "updated"],
    requiredOnCreate: ["scope", "ip_hash", "reset_at"],
    updatableColumns: ["count", "reset_at"],
  },
  users: {
    table: "users",
    primaryKey: ["id"],
    columns: [
      "id",
      "email",
      "name",
      "password_hash",
      "admin",
      "must_change_password",
      "verified",
      "created",
      "updated",
    ],
    requiredOnCreate: ["id", "email", "password_hash"],
    updatableColumns: [
      "email",
      "name",
      "password_hash",
      "admin",
      "must_change_password",
      "verified",
    ],
    hiddenOnRead: ["password_hash"],
  },
};

module.exports = entities;
